/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Linux, amd64, clang */
/* Command for C compiler:
   /home/nick/Projects/nudl/nudlcc -c -w -ferror-limit=3 -O3   -I/home/nick/.choosenim/toolchains/nim-1.6.6/lib -I/home/nick/Projects/nudl/src -o /home/nick/Projects/nudl/nudl_cache/@m..@s..@s..@s.nimble@spkgs@snimcuda-0.1.8@snimcuda@scuda_runtime_api.nim.c.o /home/nick/Projects/nudl/nudl_cache/@m..@s..@s..@s.nimble@spkgs@snimcuda-0.1.8@snimcuda@scuda_runtime_api.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU16 tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw;
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__w5wKwSbvwgGg4p9asctWQww) (void* devPtr);
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__62OF0HYXnLjBgHMTj7yNWA) (void** devPtr, size_t size);
typedef NU8 tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ;
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__gMzEGlctT8SVpwjkecJ8LQ) (void* dst, void* src, size_t count, tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ kind);
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__ia3mBRyGdwbIi5PEVF0SiA) (void);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
STRING_LITERAL(TM__D1I0yWAV9aag3RJ86BWiZWg_4, "libcudart.so", 12);
STRING_LITERAL(TM__D1I0yWAV9aag3RJ86BWiZWg_5, "libcudart.so", 12);
static void* TM__D1I0yWAV9aag3RJ86BWiZWg_2;
tyProc__w5wKwSbvwgGg4p9asctWQww Dl_1006633178_;
tyProc__62OF0HYXnLjBgHMTj7yNWA Dl_1006633161_;
tyProc__gMzEGlctT8SVpwjkecJ8LQ Dl_1006633239_;
tyProc__ia3mBRyGdwbIi5PEVF0SiA Dl_1006632970_;
N_LIB_PRIVATE N_NIMCALL(void, nimcuda_cuda_runtime_apiDatInit000)(void) {
if (!((TM__D1I0yWAV9aag3RJ86BWiZWg_2 = nimLoadLibrary(((NimStringDesc*) &TM__D1I0yWAV9aag3RJ86BWiZWg_4)))
)) nimLoadLibraryError(((NimStringDesc*) &TM__D1I0yWAV9aag3RJ86BWiZWg_5));
	Dl_1006633178_ = (tyProc__w5wKwSbvwgGg4p9asctWQww) nimGetProcAddr(TM__D1I0yWAV9aag3RJ86BWiZWg_2, "cudaFree");
	Dl_1006633161_ = (tyProc__62OF0HYXnLjBgHMTj7yNWA) nimGetProcAddr(TM__D1I0yWAV9aag3RJ86BWiZWg_2, "cudaMalloc");
	Dl_1006633239_ = (tyProc__gMzEGlctT8SVpwjkecJ8LQ) nimGetProcAddr(TM__D1I0yWAV9aag3RJ86BWiZWg_2, "cudaMemcpy");
	Dl_1006632970_ = (tyProc__ia3mBRyGdwbIi5PEVF0SiA) nimGetProcAddr(TM__D1I0yWAV9aag3RJ86BWiZWg_2, "cudaDeviceSynchronize");
}

