/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Linux, amd64, clang */
/* Command for C compiler:
   /home/nick/Projects/nudl/nudlcc -c -w -ferror-limit=3 -O3   -I/home/nick/.choosenim/toolchains/nim-1.6.6/lib -I/home/nick/Projects/nudl/src -o /home/nick/Projects/nudl/nudl_cache/@m..@s..@s..@s.nimble@spkgs@snimcuda-0.1.8@snimcuda@sdriver_types.nim.c.o /home/nick/Projects/nudl/nudl_cache/@m..@s..@s..@s.nimble@spkgs@snimcuda-0.1.8@snimcuda@sdriver_types.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU16 tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE TNimType NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_;
N_LIB_PRIVATE N_NIMCALL(void, nimcuda_driver_typesDatInit000)(void) {
static TNimNode* TM__6KzpAdahOuy3xVurQuZIsQ_2_81[81];
NI TM__6KzpAdahOuy3xVurQuZIsQ_4;
static char* NIM_CONST TM__6KzpAdahOuy3xVurQuZIsQ_3[81] = {
"cudaSuccess", 
"cudaErrorMissingConfiguration", 
"cudaErrorMemoryAllocation", 
"cudaErrorInitializationError", 
"cudaErrorLaunchFailure", 
"cudaErrorPriorLaunchFailure", 
"cudaErrorLaunchTimeout", 
"cudaErrorLaunchOutOfResources", 
"cudaErrorInvalidDeviceFunction", 
"cudaErrorInvalidConfiguration", 
"cudaErrorInvalidDevice", 
"cudaErrorInvalidValue", 
"cudaErrorInvalidPitchValue", 
"cudaErrorInvalidSymbol", 
"cudaErrorMapBufferObjectFailed", 
"cudaErrorUnmapBufferObjectFailed", 
"cudaErrorInvalidHostPointer", 
"cudaErrorInvalidDevicePointer", 
"cudaErrorInvalidTexture", 
"cudaErrorInvalidTextureBinding", 
"cudaErrorInvalidChannelDescriptor", 
"cudaErrorInvalidMemcpyDirection", 
"cudaErrorAddressOfConstant", 
"cudaErrorTextureFetchFailed", 
"cudaErrorTextureNotBound", 
"cudaErrorSynchronizationError", 
"cudaErrorInvalidFilterSetting", 
"cudaErrorInvalidNormSetting", 
"cudaErrorMixedDeviceExecution", 
"cudaErrorCudartUnloading", 
"cudaErrorUnknown", 
"cudaErrorNotYetImplemented", 
"cudaErrorMemoryValueTooLarge", 
"cudaErrorInvalidResourceHandle", 
"cudaErrorNotReady", 
"cudaErrorInsufficientDriver", 
"cudaErrorSetOnActiveProcess", 
"cudaErrorInvalidSurface", 
"cudaErrorNoDevice", 
"cudaErrorECCUncorrectable", 
"cudaErrorSharedObjectSymbolNotFound", 
"cudaErrorSharedObjectInitFailed", 
"cudaErrorUnsupportedLimit", 
"cudaErrorDuplicateVariableName", 
"cudaErrorDuplicateTextureName", 
"cudaErrorDuplicateSurfaceName", 
"cudaErrorDevicesUnavailable", 
"cudaErrorInvalidKernelImage", 
"cudaErrorNoKernelImageForDevice", 
"cudaErrorIncompatibleDriverContext", 
"cudaErrorPeerAccessAlreadyEnabled", 
"cudaErrorPeerAccessNotEnabled", 
"cudaErrorDeviceAlreadyInUse", 
"cudaErrorProfilerDisabled", 
"cudaErrorProfilerNotInitialized", 
"cudaErrorProfilerAlreadyStarted", 
"cudaErrorProfilerAlreadyStopped", 
"cudaErrorAssert", 
"cudaErrorTooManyPeers", 
"cudaErrorHostMemoryAlreadyRegistered", 
"cudaErrorHostMemoryNotRegistered", 
"cudaErrorOperatingSystem", 
"cudaErrorPeerAccessUnsupported", 
"cudaErrorLaunchMaxDepthExceeded", 
"cudaErrorLaunchFileScopedTex", 
"cudaErrorLaunchFileScopedSurf", 
"cudaErrorSyncDepthExceeded", 
"cudaErrorLaunchPendingCountExceeded", 
"cudaErrorNotPermitted", 
"cudaErrorNotSupported", 
"cudaErrorHardwareStackError", 
"cudaErrorIllegalInstruction", 
"cudaErrorMisalignedAddress", 
"cudaErrorInvalidAddressSpace", 
"cudaErrorInvalidPc", 
"cudaErrorIllegalAddress", 
"cudaErrorInvalidPtx", 
"cudaErrorInvalidGraphicsContext", 
"cudaErrorNvlinkUncorrectable", 
"cudaErrorStartupFailure", 
"cudaErrorApiFailureBase"};
static TNimNode TM__6KzpAdahOuy3xVurQuZIsQ_0[82];
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.size = sizeof(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw);
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.align = NIM_ALIGNOF(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw);
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.kind = 14;
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.base = 0;
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.flags = 3;
for (TM__6KzpAdahOuy3xVurQuZIsQ_4 = 0; TM__6KzpAdahOuy3xVurQuZIsQ_4 < 81; TM__6KzpAdahOuy3xVurQuZIsQ_4++) {
TM__6KzpAdahOuy3xVurQuZIsQ_0[TM__6KzpAdahOuy3xVurQuZIsQ_4+0].kind = 1;
TM__6KzpAdahOuy3xVurQuZIsQ_0[TM__6KzpAdahOuy3xVurQuZIsQ_4+0].offset = TM__6KzpAdahOuy3xVurQuZIsQ_4;
TM__6KzpAdahOuy3xVurQuZIsQ_0[TM__6KzpAdahOuy3xVurQuZIsQ_4+0].name = TM__6KzpAdahOuy3xVurQuZIsQ_3[TM__6KzpAdahOuy3xVurQuZIsQ_4];
TM__6KzpAdahOuy3xVurQuZIsQ_2_81[TM__6KzpAdahOuy3xVurQuZIsQ_4] = &TM__6KzpAdahOuy3xVurQuZIsQ_0[TM__6KzpAdahOuy3xVurQuZIsQ_4+0];
}
TM__6KzpAdahOuy3xVurQuZIsQ_0[0].offset = 0;
TM__6KzpAdahOuy3xVurQuZIsQ_0[1].offset = 1;
TM__6KzpAdahOuy3xVurQuZIsQ_0[2].offset = 2;
TM__6KzpAdahOuy3xVurQuZIsQ_0[3].offset = 3;
TM__6KzpAdahOuy3xVurQuZIsQ_0[4].offset = 4;
TM__6KzpAdahOuy3xVurQuZIsQ_0[5].offset = 5;
TM__6KzpAdahOuy3xVurQuZIsQ_0[6].offset = 6;
TM__6KzpAdahOuy3xVurQuZIsQ_0[7].offset = 7;
TM__6KzpAdahOuy3xVurQuZIsQ_0[8].offset = 8;
TM__6KzpAdahOuy3xVurQuZIsQ_0[9].offset = 9;
TM__6KzpAdahOuy3xVurQuZIsQ_0[10].offset = 10;
TM__6KzpAdahOuy3xVurQuZIsQ_0[11].offset = 11;
TM__6KzpAdahOuy3xVurQuZIsQ_0[12].offset = 12;
TM__6KzpAdahOuy3xVurQuZIsQ_0[13].offset = 13;
TM__6KzpAdahOuy3xVurQuZIsQ_0[14].offset = 14;
TM__6KzpAdahOuy3xVurQuZIsQ_0[15].offset = 15;
TM__6KzpAdahOuy3xVurQuZIsQ_0[16].offset = 16;
TM__6KzpAdahOuy3xVurQuZIsQ_0[17].offset = 17;
TM__6KzpAdahOuy3xVurQuZIsQ_0[18].offset = 18;
TM__6KzpAdahOuy3xVurQuZIsQ_0[19].offset = 19;
TM__6KzpAdahOuy3xVurQuZIsQ_0[20].offset = 20;
TM__6KzpAdahOuy3xVurQuZIsQ_0[21].offset = 21;
TM__6KzpAdahOuy3xVurQuZIsQ_0[22].offset = 22;
TM__6KzpAdahOuy3xVurQuZIsQ_0[23].offset = 23;
TM__6KzpAdahOuy3xVurQuZIsQ_0[24].offset = 24;
TM__6KzpAdahOuy3xVurQuZIsQ_0[25].offset = 25;
TM__6KzpAdahOuy3xVurQuZIsQ_0[26].offset = 26;
TM__6KzpAdahOuy3xVurQuZIsQ_0[27].offset = 27;
TM__6KzpAdahOuy3xVurQuZIsQ_0[28].offset = 28;
TM__6KzpAdahOuy3xVurQuZIsQ_0[29].offset = 29;
TM__6KzpAdahOuy3xVurQuZIsQ_0[30].offset = 30;
TM__6KzpAdahOuy3xVurQuZIsQ_0[31].offset = 31;
TM__6KzpAdahOuy3xVurQuZIsQ_0[32].offset = 32;
TM__6KzpAdahOuy3xVurQuZIsQ_0[33].offset = 33;
TM__6KzpAdahOuy3xVurQuZIsQ_0[34].offset = 34;
TM__6KzpAdahOuy3xVurQuZIsQ_0[35].offset = 35;
TM__6KzpAdahOuy3xVurQuZIsQ_0[36].offset = 36;
TM__6KzpAdahOuy3xVurQuZIsQ_0[37].offset = 37;
TM__6KzpAdahOuy3xVurQuZIsQ_0[38].offset = 38;
TM__6KzpAdahOuy3xVurQuZIsQ_0[39].offset = 39;
TM__6KzpAdahOuy3xVurQuZIsQ_0[40].offset = 40;
TM__6KzpAdahOuy3xVurQuZIsQ_0[41].offset = 41;
TM__6KzpAdahOuy3xVurQuZIsQ_0[42].offset = 42;
TM__6KzpAdahOuy3xVurQuZIsQ_0[43].offset = 43;
TM__6KzpAdahOuy3xVurQuZIsQ_0[44].offset = 44;
TM__6KzpAdahOuy3xVurQuZIsQ_0[45].offset = 45;
TM__6KzpAdahOuy3xVurQuZIsQ_0[46].offset = 46;
TM__6KzpAdahOuy3xVurQuZIsQ_0[47].offset = 47;
TM__6KzpAdahOuy3xVurQuZIsQ_0[48].offset = 48;
TM__6KzpAdahOuy3xVurQuZIsQ_0[49].offset = 49;
TM__6KzpAdahOuy3xVurQuZIsQ_0[50].offset = 50;
TM__6KzpAdahOuy3xVurQuZIsQ_0[51].offset = 51;
TM__6KzpAdahOuy3xVurQuZIsQ_0[52].offset = 54;
TM__6KzpAdahOuy3xVurQuZIsQ_0[53].offset = 55;
TM__6KzpAdahOuy3xVurQuZIsQ_0[54].offset = 56;
TM__6KzpAdahOuy3xVurQuZIsQ_0[55].offset = 57;
TM__6KzpAdahOuy3xVurQuZIsQ_0[56].offset = 58;
TM__6KzpAdahOuy3xVurQuZIsQ_0[57].offset = 59;
TM__6KzpAdahOuy3xVurQuZIsQ_0[58].offset = 60;
TM__6KzpAdahOuy3xVurQuZIsQ_0[59].offset = 61;
TM__6KzpAdahOuy3xVurQuZIsQ_0[60].offset = 62;
TM__6KzpAdahOuy3xVurQuZIsQ_0[61].offset = 63;
TM__6KzpAdahOuy3xVurQuZIsQ_0[62].offset = 64;
TM__6KzpAdahOuy3xVurQuZIsQ_0[63].offset = 65;
TM__6KzpAdahOuy3xVurQuZIsQ_0[64].offset = 66;
TM__6KzpAdahOuy3xVurQuZIsQ_0[65].offset = 67;
TM__6KzpAdahOuy3xVurQuZIsQ_0[66].offset = 68;
TM__6KzpAdahOuy3xVurQuZIsQ_0[67].offset = 69;
TM__6KzpAdahOuy3xVurQuZIsQ_0[68].offset = 70;
TM__6KzpAdahOuy3xVurQuZIsQ_0[69].offset = 71;
TM__6KzpAdahOuy3xVurQuZIsQ_0[70].offset = 72;
TM__6KzpAdahOuy3xVurQuZIsQ_0[71].offset = 73;
TM__6KzpAdahOuy3xVurQuZIsQ_0[72].offset = 74;
TM__6KzpAdahOuy3xVurQuZIsQ_0[73].offset = 75;
TM__6KzpAdahOuy3xVurQuZIsQ_0[74].offset = 76;
TM__6KzpAdahOuy3xVurQuZIsQ_0[75].offset = 77;
TM__6KzpAdahOuy3xVurQuZIsQ_0[76].offset = 78;
TM__6KzpAdahOuy3xVurQuZIsQ_0[77].offset = 79;
TM__6KzpAdahOuy3xVurQuZIsQ_0[78].offset = 80;
TM__6KzpAdahOuy3xVurQuZIsQ_0[79].offset = 127;
TM__6KzpAdahOuy3xVurQuZIsQ_0[80].offset = 10000;
TM__6KzpAdahOuy3xVurQuZIsQ_0[81].len = 81; TM__6KzpAdahOuy3xVurQuZIsQ_0[81].kind = 2; TM__6KzpAdahOuy3xVurQuZIsQ_0[81].sons = &TM__6KzpAdahOuy3xVurQuZIsQ_2_81[0];
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.node = &TM__6KzpAdahOuy3xVurQuZIsQ_0[81];
NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_.flags = 1<<2;
}

