/* Generated by Nim Compiler v1.6.6 */
/* Compiled for: Linux, amd64, clang */
/* Command for C compiler:
   /home/nick/Projects/nudl/nudlcc -c -w -ferror-limit=3 -O3   -I/home/nick/.choosenim/toolchains/nim-1.6.6/lib -I/home/nick/Projects/nudl/src -o /home/nick/Projects/nudl/nudl_cache/@mcuda.nim.c.o /home/nick/Projects/nudl/nudl_cache/@mcuda.nim.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include "vector_types.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__9b20qn00atr1Y9aO6SVWHVKQ tySequence__9b20qn00atr1Y9aO6SVWHVKQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw;
typedef struct tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(float, ClP_0) (NI x_0, void* ClE_0);
void* ClE_0;
} tyProc__Fpnv84eqeCeTBZxJq6ej5w;
typedef N_CLOSURE_PTR(float, TM__79bKCMut2DS9a9b9anQztCDhAA_2) (NI x_0);
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
typedef N_CLOSURE_PTR(float, TM__79bKCMut2DS9a9b9anQztCDhAA_8) (NI x_0, void* ClE_0);
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw {
float** data;
NI len;
};
typedef NU16 tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw;
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__w5wKwSbvwgGg4p9asctWQww) (void* devPtr);
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ {
  tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__62OF0HYXnLjBgHMTj7yNWA) (void** devPtr, size_t size);
typedef NU8 tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ;
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__gMzEGlctT8SVpwjkecJ8LQ) (void* dst, void* src, size_t count, tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ kind);
typedef N_CDECL_PTR(tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw, tyProc__ia3mBRyGdwbIi5PEVF0SiA) (void);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__9b20qn00atr1Y9aO6SVWHVKQ {
  TGenericSeq Sup;
  float data[SEQ_DECL_SIZE];
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};

void cuda_square(int bpg, int tpb, float * d_out, float * d_in){
    __nimcudaglobal__square<<<bpg,tpb>>>(d_out, d_in);
}

static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, __nudlglobal__square)(float* d_out, float* d_in);
N_LIB_PRIVATE N_NIMCALL(void, main__cuda_103)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*, newSeq__cuda_108)(NI len);
static N_NIMCALL(void, Marker_tySequence__9b20qn00atr1Y9aO6SVWHVKQ)(void* p, NI op);
static N_INLINE(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*, map__cuda_336)(NI* s, NI sLen_0, tyProc__Fpnv84eqeCeTBZxJq6ej5w op);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___cuda_230)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, newSeq__cuda_293)(NI len);
static N_NIMCALL(void, Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op);
static N_INLINE(NI, len__cuda_281)(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x_0);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(float, colonanonymous___cuda_328)(NI x_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___cuda_417)(tySequence__9b20qn00atr1Y9aO6SVWHVKQ* x_0);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, cuda__cuda_471)(tySequence__9b20qn00atr1Y9aO6SVWHVKQ* s, tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw* Result);
N_LIB_PRIVATE N_NIMCALL(void, newGpuArray__cuda_477)(NI len, tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw* Result);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, deallocCuda__cuda_481)(float** p);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5303)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5265)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5310)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5308)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5259)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(float*, cudaMalloc__cuda_530)(NI size);
N_NIMCALL(void, cuda_square)(int bpg, int tpb, float* y_0, float* x_0);
N_LIB_PRIVATE N_NIMCALL(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*, cpu__cuda_609)(tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw g);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimcuda_driver_typesDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimcuda_cuda_runtime_apiDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimcuda_nimcudaDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, cudaDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
extern TNimType NTIcfloat__QtYy0tMSFgmwjwM3pcEGhw_;
N_LIB_PRIVATE TNimType NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_;
extern TNimType NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_;
extern TNimType NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_;
extern TNimType NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_;
STRING_LITERAL(TM__79bKCMut2DS9a9b9anQztCDhAA_9, " ", 1);
extern TNimType NTIrefptrcfloat__3pb9aFINgLhYxDzF9cz7Elmw_;
extern tyProc__w5wKwSbvwgGg4p9asctWQww Dl_1006633178_;
extern tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5212;
extern tyProc__62OF0HYXnLjBgHMTj7yNWA Dl_1006633161_;
extern tyProc__gMzEGlctT8SVpwjkecJ8LQ Dl_1006633239_;
extern tyProc__ia3mBRyGdwbIi5PEVF0SiA Dl_1006632970_;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, __nudlglobal__square)(float* d_out, float* d_in) {
	unsigned int idx;
	NU offset;
	float* in_addr;
	float* out_addr;
	float f;
	idx = threadIdx.x;
	offset = (NU)((NU64)(((NU) (idx))) * (NU64)(((NU) (((NI) 4)))));
	in_addr = ((float*) ((NU)((NU64)(((NU) (ptrdiff_t) (d_in))) + (NU64)(offset))));
	out_addr = ((float*) ((NU)((NU64)(((NU) (ptrdiff_t) (d_out))) + (NU64)(offset))));
	f = (*in_addr);
	(*out_addr) = ((NF32)(f) * (NF32)(f));
}
static N_NIMCALL(void, Marker_tySequence__9b20qn00atr1Y9aO6SVWHVKQ)(void* p, NI op) {
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* a;
	NI T1_;
	a = (tySequence__9b20qn00atr1Y9aO6SVWHVKQ*)p;
	T1_ = (NI)0;
}
static N_INLINE(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*, map__cuda_336)(NI* s, NI sLen_0, tyProc__Fpnv84eqeCeTBZxJq6ej5w op) {
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* result;
	result = NIM_NIL;
	if ((sLen_0) < ((NI) 0) || (sLen_0) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(sLen_0, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = (tySequence__9b20qn00atr1Y9aO6SVWHVKQ*) newSeq((&NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_), ((NI) (sLen_0)));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = sLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__79bKCMut2DS9a9b9anQztCDhAA_3;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				if (i < 0 || i >= (result ? result->Sup.len : 0)){ raiseIndexError2(i,(result ? result->Sup.len : 0)-1); }
				if (i < 0 || i >= sLen_0){ raiseIndexError2(i,sLen_0-1); }
				result->data[i] = op.ClE_0? op.ClP_0(s[i], op.ClE_0):((TM__79bKCMut2DS9a9b9anQztCDhAA_2)(op.ClP_0))(s[i]);
				if (nimAddInt(i_2, ((NI) 1), &TM__79bKCMut2DS9a9b9anQztCDhAA_3)) { raiseOverflow(); };
				i_2 = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_3);
			} LA3: ;
		}
	}
	return result;
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___cuda_230)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
static N_NIMCALL(void, Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g)(void* p, NI op) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* a;
	NI T1_;
	a = (tySequence__qwqHTkRvwhrRyENtudHQ7g*)p;
	T1_ = (NI)0;
}
static N_INLINE(NI, len__cuda_281)(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x_0) {
	NI result;
	NI TM__79bKCMut2DS9a9b9anQztCDhAA_4;
	NI TM__79bKCMut2DS9a9b9anQztCDhAA_5;
	result = (NI)0;
	if (nimSubInt(x_0.b, x_0.a, &TM__79bKCMut2DS9a9b9anQztCDhAA_4)) { raiseOverflow(); };
	if (nimAddInt((NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_4), ((NI) 1), &TM__79bKCMut2DS9a9b9anQztCDhAA_5)) { raiseOverflow(); };
	result = ((((NI) 0) >= (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_5)) ? ((NI) 0) : (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_5));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(float, colonanonymous___cuda_328)(NI x_0) {
	float result;
	result = (float)0;
	result = ((float) (x_0));
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5303)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5265)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5308)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5259((&gch__system_5212.zct), c);
}
static N_INLINE(void, decRef__system_5310)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5308(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5265(src);
		incRef__system_5303(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5265((*dest));
		decRef__system_5310(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, deallocCuda__cuda_481)(float** p) {
	{
		tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw yX60gensym13_;
		if (!!(((*p) == 0))) goto LA3_;
		yX60gensym13_ = Dl_1006633178_(((void*) ((*p))));
		{
			tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ* T9_;
			NimStringDesc* T10_;
			NimStringDesc* T11_;
			if (!!((yX60gensym13_ == ((tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw) 0)))) goto LA7_;
			T9_ = NIM_NIL;
			T9_ = (tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ*) newObj((&NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_), sizeof(tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ));
			(*T9_).Sup.Sup.Sup.Sup.m_type = (&NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_);
			(*T9_).Sup.Sup.Sup.name = "CudaError";
			T10_ = NIM_NIL;
			T11_ = NIM_NIL;
			T11_ = dollar___systemZdollars_3(((NI) (yX60gensym13_)));
			T10_ = rawNewString((reprEnum((NI)yX60gensym13_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)) ? reprEnum((NI)yX60gensym13_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_))->Sup.len : 0) + (T11_ ? T11_->Sup.len : 0) + 1);
appendString(T10_, reprEnum((NI)yX60gensym13_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)));
appendString(T10_, ((NimStringDesc*) &TM__79bKCMut2DS9a9b9anQztCDhAA_9));
appendString(T10_, T11_);
			asgnRef((void**) (&(*T9_).Sup.Sup.Sup.message), T10_);
			asgnRef((void**) (&(*T9_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T9_, "CudaError", "deallocCuda", "nimcuda.nim", 50);
		}
		LA7_: ;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(float*, cudaMalloc__cuda_530)(NI size) {
	float* result;
	NI s;
	NI TM__79bKCMut2DS9a9b9anQztCDhAA_10;
	tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw yX60gensym16_;
	result = (float*)0;
	if (nimMulInt(size, ((NI) 4), &TM__79bKCMut2DS9a9b9anQztCDhAA_10)) { raiseOverflow(); };
	s = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_10);
	yX60gensym16_ = Dl_1006633161_(((void**) (&result)), s);
	{
		tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ* T5_;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		if (!!((yX60gensym16_ == ((tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw) 0)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ*) newObj((&NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_), sizeof(tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_);
		(*T5_).Sup.Sup.Sup.name = "CudaError";
		T6_ = NIM_NIL;
		T7_ = NIM_NIL;
		T7_ = dollar___systemZdollars_3(((NI) (yX60gensym16_)));
		T6_ = rawNewString((reprEnum((NI)yX60gensym16_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)) ? reprEnum((NI)yX60gensym16_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_))->Sup.len : 0) + (T7_ ? T7_->Sup.len : 0) + 1);
appendString(T6_, reprEnum((NI)yX60gensym16_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)));
appendString(T6_, ((NimStringDesc*) &TM__79bKCMut2DS9a9b9anQztCDhAA_9));
appendString(T6_, T7_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.message), T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "CudaError", "cudaMalloc", "nimcuda.nim", 50);
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, newGpuArray__cuda_477)(NI len, tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw* Result) {
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).len = 0;
	unsureAsgnRef((void**) (&(*Result).data), (float**) newObj((&NTIrefptrcfloat__3pb9aFINgLhYxDzF9cz7Elmw_), sizeof(float*)));
	(*Result).len = len;
	(*(*Result).data) = cudaMalloc__cuda_530((*Result).len);
}
N_LIB_PRIVATE N_NIMCALL(void, cuda__cuda_471)(tySequence__9b20qn00atr1Y9aO6SVWHVKQ* s, tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw* Result) {
	NI T1_;
	NI size;
	NI TM__79bKCMut2DS9a9b9anQztCDhAA_11;
	tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw yX60gensym19_;
	T1_ = (s ? s->Sup.len : 0);
	newGpuArray__cuda_477(T1_, Result);
	if (nimMulInt((*Result).len, ((NI) 4), &TM__79bKCMut2DS9a9b9anQztCDhAA_11)) { raiseOverflow(); };
	size = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_11);
	if (((NI) 0) < 0 || ((NI) 0) >= (s ? s->Sup.len : 0)){ raiseIndexError2(((NI) 0),(s ? s->Sup.len : 0)-1); }
	yX60gensym19_ = Dl_1006633239_(((void*) ((*(*Result).data))), ((void*) ((&s->data[((NI) 0)]))), size, ((tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ) 1));
	{
		tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ* T6_;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		if (!!((yX60gensym19_ == ((tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw) 0)))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ*) newObj((&NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_), sizeof(tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ));
		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_);
		(*T6_).Sup.Sup.Sup.name = "CudaError";
		T7_ = NIM_NIL;
		T8_ = NIM_NIL;
		T8_ = dollar___systemZdollars_3(((NI) (yX60gensym19_)));
		T7_ = rawNewString((reprEnum((NI)yX60gensym19_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)) ? reprEnum((NI)yX60gensym19_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_))->Sup.len : 0) + (T8_ ? T8_->Sup.len : 0) + 1);
appendString(T7_, reprEnum((NI)yX60gensym19_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)));
appendString(T7_, ((NimStringDesc*) &TM__79bKCMut2DS9a9b9anQztCDhAA_9));
appendString(T7_, T8_);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.message), T7_);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T6_, "CudaError", "cuda", "nimcuda.nim", 50);
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*, cpu__cuda_609)(tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw g) {
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* result;
	NI size;
	NI T1_;
	NI TM__79bKCMut2DS9a9b9anQztCDhAA_12;
	tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw yX60gensym25_;
	result = NIM_NIL;
	if ((g.len) < ((NI) 0) || (g.len) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(g.len, ((NI) 0), ((NI) IL64(9223372036854775807))); }
	result = newSeq__cuda_108(((NI) (g.len)));
	T1_ = (result ? result->Sup.len : 0);
	if (nimMulInt(T1_, ((NI) 4), &TM__79bKCMut2DS9a9b9anQztCDhAA_12)) { raiseOverflow(); };
	size = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_12);
	if (((NI) 0) < 0 || ((NI) 0) >= (result ? result->Sup.len : 0)){ raiseIndexError2(((NI) 0),(result ? result->Sup.len : 0)-1); }
	yX60gensym25_ = Dl_1006633239_(((void*) ((&result->data[((NI) 0)]))), ((void*) ((*g.data))), size, ((tyEnum_cudaMemcpyKind__yB1HLaFI6fD2UwPFT7vdfQ) 2));
	{
		tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ* T6_;
		NimStringDesc* T7_;
		NimStringDesc* T8_;
		if (!!((yX60gensym25_ == ((tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw) 0)))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ*) newObj((&NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_), sizeof(tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ));
		(*T6_).Sup.Sup.Sup.Sup.m_type = (&NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_);
		(*T6_).Sup.Sup.Sup.name = "CudaError";
		T7_ = NIM_NIL;
		T8_ = NIM_NIL;
		T8_ = dollar___systemZdollars_3(((NI) (yX60gensym25_)));
		T7_ = rawNewString((reprEnum((NI)yX60gensym25_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)) ? reprEnum((NI)yX60gensym25_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_))->Sup.len : 0) + (T8_ ? T8_->Sup.len : 0) + 1);
appendString(T7_, reprEnum((NI)yX60gensym25_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)));
appendString(T7_, ((NimStringDesc*) &TM__79bKCMut2DS9a9b9anQztCDhAA_9));
appendString(T7_, T8_);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.message), T7_);
		asgnRef((void**) (&(*T6_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T6_, "CudaError", "cpu", "nimcuda.nim", 50);
	}
	LA4_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, main__cuda_103)(void) {
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* a;
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* b;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* T1_;
	tyProc__Fpnv84eqeCeTBZxJq6ej5w T8_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T9_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T10_;
	tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw u;
	tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw v;
	tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw yX60gensym22_;
	tySequence__9b20qn00atr1Y9aO6SVWHVKQ* z_1;
	tyArray__nHXaesL0DJZHyVS07ARPRA T18_;
	a = newSeq__cuda_108(((NI) 64));
	T1_ = NIM_NIL;
	{
		tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA colontmp_;
		NI iX60gensym4_;
		tySequence__qwqHTkRvwhrRyENtudHQ7g* resultX60gensym4_;
		NI T3_;
		colontmp_ = dotdot___cuda_230(((NI) 0), ((NI) 63));
		iX60gensym4_ = ((NI) 0);
		T3_ = (NI)0;
		T3_ = len__cuda_281(colontmp_);
		if ((T3_) < ((NI) 0) || (T3_) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI(T3_, ((NI) 0), ((NI) IL64(9223372036854775807))); }
		resultX60gensym4_ = newSeq__cuda_293(((NI) (T3_)));
		{
			NI itX60gensym4_;
			itX60gensym4_ = (NI)0;
			{
				NI x_1;
				NI res;
				x_1 = (NI)0;
				res = colontmp_.a;
				{
					while (1) {
						NI TM__79bKCMut2DS9a9b9anQztCDhAA_6;
						NI TM__79bKCMut2DS9a9b9anQztCDhAA_7;
						if (!(res <= colontmp_.b)) goto LA7;
						x_1 = res;
						itX60gensym4_ = x_1;
						if (iX60gensym4_ < 0 || iX60gensym4_ >= (resultX60gensym4_ ? resultX60gensym4_->Sup.len : 0)){ raiseIndexError2(iX60gensym4_,(resultX60gensym4_ ? resultX60gensym4_->Sup.len : 0)-1); }
						resultX60gensym4_->data[iX60gensym4_] = itX60gensym4_;
						if (nimAddInt(iX60gensym4_, ((NI) 1), &TM__79bKCMut2DS9a9b9anQztCDhAA_6)) { raiseOverflow(); };
						iX60gensym4_ = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_6);
						if (nimAddInt(res, ((NI) 1), &TM__79bKCMut2DS9a9b9anQztCDhAA_7)) { raiseOverflow(); };
						res = (NI)(TM__79bKCMut2DS9a9b9anQztCDhAA_7);
					} LA7: ;
				}
			}
		}
		genericSeqAssign((&T1_), resultX60gensym4_, (&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_));
	}
	nimZeroMem((void*)(&T8_), sizeof(tyProc__Fpnv84eqeCeTBZxJq6ej5w));
	T8_.ClP_0 = ((TM__79bKCMut2DS9a9b9anQztCDhAA_8) (colonanonymous___cuda_328)); T8_.ClE_0 = NIM_NIL;
	b = map__cuda_336(T1_->data, (T1_ ? T1_->Sup.len : 0), T8_);
	nimZeroMem((void*)T9_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T9_[0] = dollar___cuda_417(a);
	echoBinSafe(T9_, 1);
	nimZeroMem((void*)T10_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T10_[0] = dollar___cuda_417(b);
	echoBinSafe(T10_, 1);
	nimZeroMem((void*)(&u), sizeof(tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw));
	cuda__cuda_471(a, (&u));
	nimZeroMem((void*)(&v), sizeof(tyObject_GpuArray__lWDvSuvBMFF9bQhHJV1telw));
	cuda__cuda_471(b, (&v));
	cuda_square(((int) 1), ((int) 64), (*u.data), (*v.data));
	yX60gensym22_ = Dl_1006632970_();
	{
		tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ* T15_;
		NimStringDesc* T16_;
		NimStringDesc* T17_;
		if (!!((yX60gensym22_ == ((tyEnum_cudaError__fqColDLJ7o0O5tgPgrg8tw) 0)))) goto LA13_;
		T15_ = NIM_NIL;
		T15_ = (tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ*) newObj((&NTIrefcudaerror__L9aLneJnpBIJFkSwgYQgzvA_), sizeof(tyObject_CudaError__uH4At6Xfefy9bj0ZsCuY3DQ));
		(*T15_).Sup.Sup.Sup.Sup.m_type = (&NTIcudaerror__uH4At6Xfefy9bj0ZsCuY3DQ_);
		(*T15_).Sup.Sup.Sup.name = "CudaError";
		T16_ = NIM_NIL;
		T17_ = NIM_NIL;
		T17_ = dollar___systemZdollars_3(((NI) (yX60gensym22_)));
		T16_ = rawNewString((reprEnum((NI)yX60gensym22_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)) ? reprEnum((NI)yX60gensym22_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_))->Sup.len : 0) + (T17_ ? T17_->Sup.len : 0) + 1);
appendString(T16_, reprEnum((NI)yX60gensym22_, (&NTIcudaerror__fqColDLJ7o0O5tgPgrg8tw_)));
appendString(T16_, ((NimStringDesc*) &TM__79bKCMut2DS9a9b9anQztCDhAA_9));
appendString(T16_, T17_);
		asgnRef((void**) (&(*T15_).Sup.Sup.Sup.message), T16_);
		asgnRef((void**) (&(*T15_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T15_, "CudaError", "main", "nimcuda.nim", 50);
	}
	LA13_: ;
	z_1 = cpu__cuda_609(u);
	nimZeroMem((void*)T18_, sizeof(tyArray__nHXaesL0DJZHyVS07ARPRA));
	T18_[0] = dollar___cuda_417(z_1);
	echoBinSafe(T18_, 1);
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	initStackBottomWith((void *)&inner);
	systemInit000();
	nimcuda_driver_typesDatInit000();
	nimcuda_cuda_runtime_apiDatInit000();
	nimcuda_nimcudaDatInit000();
	cudaDatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	nimZeroMem((void*)(&threadIdx), sizeof(uint3));
	nimZeroMem((void*)(&blockIdx), sizeof(uint3));
	nimZeroMem((void*)(&gridDim), sizeof(dim3));
	nimZeroMem((void*)(&blockDim), sizeof(dim3));
	warpSize = 0;
	main__cuda_103();
}
}

N_LIB_PRIVATE N_NIMCALL(void, cudaDatInit000)(void) {
NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_.size = sizeof(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*);
NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_.align = NIM_ALIGNOF(tySequence__9b20qn00atr1Y9aO6SVWHVKQ*);
NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_.kind = 24;
NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_.base = (&NTIcfloat__QtYy0tMSFgmwjwM3pcEGhw_);
NTIseqLcfloatT__9b20qn00atr1Y9aO6SVWHVKQ_.marker = Marker_tySequence__9b20qn00atr1Y9aO6SVWHVKQ;
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.size = sizeof(tySequence__qwqHTkRvwhrRyENtudHQ7g*);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.align = NIM_ALIGNOF(tySequence__qwqHTkRvwhrRyENtudHQ7g*);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.kind = 24;
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.base = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_.marker = Marker_tySequence__qwqHTkRvwhrRyENtudHQ7g;
(&NTIrefptrcfloat__3pb9aFINgLhYxDzF9cz7Elmw_)->finalizer = (void*)deallocCuda__cuda_481;
}

