#!/bin/sh
rm -rf $PWD/cache

# --nimcache:$PWD/cache \
# we use our own cache just so we can read the code
nim cpp \
-d:release \
--nimcache:$PWD/cache \
--cincludes:"/opt/cuda/include" \
--cc:"clang" \
--clang.cpp.exe:$PWD/nudlcc \
--clang.cpp.linkerexe:$PWD/nudlcc \
--clang.cpp.options.debug: "-Xcompiler -Og" \
--clang.cpp.options.speed: "-Xcompiler -O3 -Xcompiler -fno-strict-aliasing" \
--clang.cpp.options.size: "-Xcompiler -Os" \
--clang.cpp.options.always:"-gencode arch=compute_61,code=sm_61 -gencode arch=compute_75,code=sm_75 --x cu -Xcompiler -fpermissive" \
src/cuda.nim