#!/bin/sh
rm -rf $PWD/cache

# --nimcache:$PWD/cache \
# we use our own cache just so we can read the code
nim c \
-d:release \
--nimcache:$PWD/cache \
--cc:gcc \
--gcc.exe: "$PWD/nudlcc" \
--gcc.linkerexe: "$PWD/nudlcc" \
--gcc.options.debug: "-Xcompiler -Og" \
--gcc.options.speed: "-Xcompiler -O3" \
--gcc.options.size: "-Xcompiler -Os" \
--gcc.options.always:"--x cu" \
src/forum.nim