#!/bin/sh
rm -rf $PWD/cache
mkdir $PWD/cache
cp $PWD/nimbase.h $PWD/cache
rm $PWD/commands.txt

nim cc \
--nimcache:$PWD/cache \
-d:release \
--cc:gcc \
--gcc.exe: "$PWD/nimnvcc" \
--gcc.linkerexe: "$PWD/nimnvcc" \
--gcc.cpp.options.debug: "-Xcompiler -Og" \
--gcc.cpp.options.speed: "-Xcompiler -O3" \
--gcc.cpp.options.size: "-Xcompiler -Os" \
--gcc.cpp.options.always:"--x cu -ccbin=gcc-5" \
src/cuda.nim